import { AbiItem } from "web3-utils";

const contract: {
  address: string,
  abi: AbiItem[],
} = {
  address: "0x32adbba23b00aa40701c5423466e4e57fdb4fe32",
  abi: [
    {
      inputs: [
        { internalType: "address", name: "_aurum", type: "address" },
        { internalType: "address", name: "_raiders", type: "address" },
        { internalType: "address", name: "_treasury", type: "address" },
        {
          internalType: "address",
          name: "_infoAddress",
          type: "address",
        },
        { internalType: "address", name: "_history", type: "address" },
        { internalType: "address", name: "_randomness", type: "address" },
        { internalType: "uint256", name: "_frequency", type: "uint256" },
        {
          internalType: "uint256",
          name: "_discountStep",
          type: "uint256",
        },
        {
          internalType: "uint256",
          name: "_gen10CostScale",
          type: "uint256",
        },
      ],
      stateMutability: "nonpayable",
      type: "constructor",
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: true,
          internalType: "address",
          name: "previousOwner",
          type: "address",
        },
        {
          indexed: true,
          internalType: "address",
          name: "newOwner",
          type: "address",
        },
      ],
      name: "OwnershipTransferred",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: false,
          internalType: "address",
          name: "account",
          type: "address",
        },
      ],
      name: "Paused",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: false,
          internalType: "uint256",
          name: "tokenId",
          type: "uint256",
        },
        {
          indexed: true,
          internalType: "uint256",
          name: "race",
          type: "uint256",
        },
        {
          indexed: true,
          internalType: "uint256",
          name: "generation",
          type: "uint256",
        },
        {
          indexed: true,
          internalType: "address",
          name: "owner",
          type: "address",
        },
      ],
      name: "RaiderRecruited",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: false,
          internalType: "address",
          name: "account",
          type: "address",
        },
      ],
      name: "Unpaused",
      type: "event",
    },
    {
      inputs: [],
      name: "AURUM_DECIMALS",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "FIRST_DISCOUNT_GENERATION",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "activeRecruitmentGeneration",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "aurumAddress",
      outputs: [{ internalType: "address", name: "", type: "address" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [
        {
          internalType: "uint256",
          name: "targetGeneration",
          type: "uint256",
        },
        {
          internalType: "uint256",
          name: "raiderGeneration",
          type: "uint256",
        },
        {
          internalType: "uint256",
          name: "gen10Recruitments",
          type: "uint256",
        },
      ],
      name: "calcRecruitment",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "uint256", name: "_raiderId", type: "uint256" }],
      name: "canRaiderRecruit",
      outputs: [{ internalType: "bool", name: "", type: "bool" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      name: "commonChars",
      outputs: [
        { internalType: "enum Recruiting.Race", name: "", type: "uint8" },
      ],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "currentRaceCounts",
      outputs: [{ internalType: "uint256[12]", name: "", type: "uint256[12]" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "discountStep",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "gen10CostScale",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      name: "generationBasesInAurum",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      name: "generationMaxDiscount",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "uint256", name: "_seed", type: "uint256" }],
      name: "getBigRandomNum",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "uint256", name: "raiderId", type: "uint256" }],
      name: "getRaiderRecruitCost",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "historyAddress",
      outputs: [{ internalType: "address", name: "", type: "address" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "infoAddress",
      outputs: [{ internalType: "address", name: "", type: "address" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "makeTreasuryInfoOwner",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [],
      name: "makeTreasuryRaidersOwner",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [
        {
          internalType: "enum Recruiting.Rarity",
          name: "",
          type: "uint8",
        },
      ],
      name: "maxSameRarity",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "uint256", name: "_raiderId", type: "uint256" }],
      name: "nextRaiderRecruitGeneration",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "uint256", name: "_raiderId", type: "uint256" }],
      name: "nextRecruitTime",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "owner",
      outputs: [{ internalType: "address", name: "", type: "address" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "pause",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [],
      name: "paused",
      outputs: [{ internalType: "bool", name: "", type: "bool" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "raidersAddress",
      outputs: [{ internalType: "address", name: "", type: "address" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "randomnessAddress",
      outputs: [{ internalType: "address", name: "", type: "address" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      name: "rareChars",
      outputs: [
        { internalType: "enum Recruiting.Race", name: "", type: "uint8" },
      ],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [
        {
          internalType: "enum Recruiting.Rarity",
          name: "",
          type: "uint8",
        },
      ],
      name: "rarityThresholds",
      outputs: [
        { internalType: "uint256", name: "total", type: "uint256" },
        { internalType: "uint256", name: "same", type: "uint256" },
        { internalType: "uint256", name: "common", type: "uint256" },
        { internalType: "uint256", name: "uncommon", type: "uint256" },
        { internalType: "uint256", name: "rare", type: "uint256" },
      ],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "uint256", name: "raiderId", type: "uint256" }],
      name: "recruitRaider",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [],
      name: "recruitingFrequency",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [
        {
          internalType: "uint256",
          name: "_currentGeneration",
          type: "uint256",
        },
        {
          internalType: "uint256",
          name: "_targetGeneration",
          type: "uint256",
        },
        {
          internalType: "uint256",
          name: "_gen10Recruitments",
          type: "uint256",
        },
      ],
      name: "recruitmentCost",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "renounceOwnership",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [{ internalType: "address", name: "newOwner", type: "address" }],
      name: "transferOwnership",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [],
      name: "treasuryAddress",
      outputs: [{ internalType: "address", name: "", type: "address" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      name: "uncommonChars",
      outputs: [
        { internalType: "enum Recruiting.Race", name: "", type: "uint8" },
      ],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "unpause",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [
        {
          internalType: "uint256",
          name: "generation_number",
          type: "uint256",
        },
      ],
      name: "updateActiveRecruitment",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [
        { internalType: "uint256", name: "generation", type: "uint256" },
        { internalType: "uint256", name: "aurumAmt", type: "uint256" },
      ],
      name: "updateAurumBaseForGeneration",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [{ internalType: "uint256", name: "newStep", type: "uint256" }],
      name: "updateDiscountStep",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [{ internalType: "uint256", name: "_scale", type: "uint256" }],
      name: "updateGen10CostScale",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [
        { internalType: "uint256", name: "generation", type: "uint256" },
        { internalType: "uint256", name: "maxDiscount", type: "uint256" },
      ],
      name: "updateMaxDiscountForGeneration",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [
        { internalType: "address", name: "_randomness", type: "address" },
      ],
      name: "updateRandomnessAddress",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [
        { internalType: "uint256", name: "_frequency", type: "uint256" },
      ],
      name: "updateRecruitingFrequency",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [{ internalType: "address", name: "_address", type: "address" }],
      name: "updateTreasuryAddress",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
  ],
};

export default contract;
